### ISSUE TITLE
Symfony 2.8 / 3.0?

### ISSUE THREAD

**Issue by drewclauson** [neomerx/limoncello-collins#19]
What needs to happen to support Symfony 2.8 and/or 3.0?  I haven't noticed any deprecation logs in my usage of this with Symfony 2.7.

Thanks!

**Comment by neomerx** [comment]
Probably nothing prevents from 2.8 and 3.0. It has so little connection with the library...

**Comment by neomerx** [comment]
BTW have you posted symfony quick app?

**Comment by drewclauson** [comment]
I haven't - I'm behind on a deadline so I had to table the quick app until I finish the deadline up. :smiley:

**Comment by neomerx** [comment]
OK, let me know when you can make the world better with the quick start app :wink:

**Comment by drewclauson** [comment]
:laughing: will do!
