### ISSUE TITLE
Schema is not registered for a resource at path ''.

### ISSUE THREAD

**Issue by jonwhittlestone** [neomerx/limoncello-collins#22]
Hi

I am attempting to replicate limoncello-collins by retracing the steps of [your commit](https://goo.gl/JvDcjJ)

I followed the steps, migrate and seeded, and visited http://idv-server.dev/api/v1/boards/1
However I received the error - Schema is not registered for a resource at path ''.

Do you know why?

I have uploaded [my limoncello-collins attempt here](https://github.com/jonwhittlestone/idv-server/commit/a379c41eaf9b9b28ce230a1639b21b0d07a32176)

Thanks

Jon

**Comment by free3-5man** [comment]
@jonwhittlestone 

do you add the limoncello.php to directory config?
the limoncello.php configured used schemas such as

S::SCHEMAS => [
        PostSchema::class,
        UserSchema::class,
        RoleSchema::class,
    ],

**Comment by neomerx** [comment]
@jonwhittlestone Most likely you try to encode a resource but encoder can't find any `Schema` for that resorce. Relationship path '' means it's a very top resource which supports my explanation.

**Comment by neomerx** [comment]
@jonwhittlestone I understand you might want to done all the steps just out of curiosity though it's easier to just take the app :wink:

**Comment by neomerx** [comment]
I'm closing the question. If you feel you have more please don't hesitate to ask.

**Comment by neomerx** [comment]
Heh, github lost my answer on this issue...

Anyways, @jonwhittlestone you most likely haven't registered `Schema` for resource you want to encoder.

I understand you might re-iterate the steps just out of curiosity though it's easier (and less errors) just to use the app as a starting point.

I'm closing the issue. If you feel you have more questions please don't hesitate to ask.
